apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp-ns
spec:
  containers:
  - name: webapp
    image: 637423303909.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: MYSQL_HOST
      value: "mysql-service.mysql-ns.svc.cluster.local"
    - name: MYSQL_USER
      value: "root"
    - name: MYSQL_PASSWORD
      value: "password123"
    - name: MYSQL_DB
      value: "employees"
    - name: DBPORT
      value: "3306"
  imagePullSecrets:
  - name: ecr-registry-secret